### ISSUE TITLE
SQL Choice Conflict in Readme

### ISSUE THREAD

**Issue by Niyusha** [amerkurev/django-docker-template#10]
"The technology stack used includes:

[....]
[PostgreSQL](https://www.postgresql.org/) ver. 15
[...]"

and 

"Another important point is the use of SQLite3 instead of Postgres (which we don't run). In our example, we add a volume named sqlite. This data is stored persistently and does not disappear between restarts of the Django development server. However, if you have a second similar project, it would be better to change the volume name from sqlite to something else so that the second project uses its own copy of the database. For example:"

It's very likely that I'm simply missing something here but these seems to be an editing mistake.

**Comment by amerkurev** [comment]
SQLite3 is used when we need to run just the Django container without PostgreSQL.

PostgreSQL is not deployed until Django is run within a Docker Compose environment, at which point PostgreSQL should also be initiated and run as part of the services defined in the `docker-compose.yml` file. Essentially, the project supports two modes of operation: one with PostgreSQL and another with SQLite3.
