### ISSUE TITLE
get_or_create() does not hash passwords

### ISSUE THREAD

**Issue by nbovee** [amerkurev/django-docker-template#20]
Heya, a small fix needed for [safecreatesuperuser.py](https://github.com/amerkurev/django-docker-template/blob/478038082abe14d308e10964270a1a2008ab7e74/website/setup/management/commands/safecreatesuperuser.py#L41).

Using `get_or_create` directly sets fields, and does not hash the password.

```shell
/usr/src/website # python manage.py dumpdata auth.user
[{
  "model": "auth.user",
  "pk": 1,
  "fields": {
    "password": "admin",
    "last_login": null, 
    "is_superuser": true,
    "username": "admin",
    "first_name": "",
    "last_name": "",
    "email": "admin@example.com",
    "is_staff": true,
    "is_active": true,
    "date_joined": "2024-06-03T21:27:21.811Z",
    "groups": [],
    "user_permissions": []
  }
}]
```

I'll have a PR in momentarily.

**Comment by amerkurev** [comment]
@nbovee Can I close this issue? I merged your last PR and it fixed this issue, didn't it?

**Comment by nbovee** [comment]
Yes I think the issue is done. I will be adding the `USER_EXISTS` checking like in `docker-cmd.sh`, for safety if users run it on an active database, but that is not a part of the bug.
