### ISSUE TITLE
Traefik dashboard

### ISSUE THREAD

**Issue by shariq1989** [amerkurev/django-docker-template#4]
Is the dashboard enabled in dev/prod? If so how can it be accessed?

**Comment by amerkurev** [comment]
I have an idea to add additional `docker-compose.***.yml` files for different scenarios in the project. For example, enabling Traefik dashboard or deploying Redis or Vault, etc. These files will not be included by default, but can be easily activated if desired. All scenarios will be collected in one place, and new ones can always be added.

If I do this, it will be very easy for you to enable Traefik dashboard :)

**Comment by shariq1989** [comment]
Sounds good! I would love to continue using this in the future.
