### ISSUE TITLE
Using a custom user model when starting a project

### ISSUE THREAD

**Issue by shariq1989** [amerkurev/django-docker-template#6]
Django recommends setting up a custom user model when starting a new project. It's easy to add in the beginning but becomes more of a hurdle later on. Thoughts on adding it in? 

https://docs.djangoproject.com/en/4.2/topics/auth/customizing/#using-a-custom-user-model-when-starting-a-project

**Comment by amerkurev** [comment]
Hi @shariq1989! I think this idea is really cool, but I'm not sure it should be a default part of the project template. See, some devs might want to do things their own way and not use AbstractUser. They might not even know it exists and just use the User model directly. To be honest, I'm not sure what the best solution is here. Maybe we should discuss this with a wider group of people to get a better understanding.

**Comment by shariq1989** [comment]
Sounds good. I'll probably add a script to set it up in a branch on my fork
