### ISSUE TITLE
Permission Issues When Running Docker Containers

### ISSUE THREAD

**Issue by Hossein-Roshandel** [amerkurev/django-docker-template#9]
I encountered two permission issues while running containers with Docker on Fedora 38. Here are the details of the problems and the solutions I applied:

1- Issue with permission to access **docker.sock** 

When I ran the following command:
```console
docker compose -f docker-compose.debug.yml up
```
I encountered the following error:
```console
"msg="Failed to retrieve information of the docker client and server host: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock"
```
To resolve this, I added privileged: true to the reverse-proxy YAML configuration in the docker-compose.debug.yml file.

2- Issue with permission to access **source files** in development container
When I ran the following command:
```console
docker run -it --rm -p 8000:8000 -v sqlite:/sqlite -v $(pwd)/website:/website django-docker-template:master python manage.py runserver 0.0.0.0:8000
```
I encountered the following error:
```console
"python: can't open file '/usr/src/website/manage.py': [Errno 13] Permission denied"
```
To resolve this, I had to change `/usr/src/website` to `/usr/src/website:z` everywhere in the YAML files and the command.

## Environment:
- Fedora 38
-  Docker  20.10.23 
-  docker-compose  1.29.2.

**Comment by code-admirer** [comment]
Hi ,
Is this issue still open ?

**Comment by Hossein-Roshandel** [comment]
I think the solution is in the description. I shall close it. Thanks
